apiVersion: v1
kind: Service
metadata:
  name: testsvc
  labels:
    app: testsvc
spec:
  clusterIP: None
  selector:
    app: testsvc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: testss
spec:
  selector:
    matchLabels:
      app: testsvc
  serviceName: "testsvc"
  replicas: 3
  template:
    metadata:
      labels:
        app: testsvc
    spec:
      containers:
      - name: testsvc
        image: nicolaka/netshoot
        command:
          - "sleep"
          - "3600"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
