# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
spec:
  containers:
  - name: test-pod
    image: nginx:alpine
    ports:
    - containerPort: 80
