# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  labels:
    name: netshoot
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep 36000"]
    ports:
    - containerPort: 80
